ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS category TEXT CHECK (category IN ('exotic', 'urban'));

INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Audi RS3 Verde', 19, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.8s", "maxSpeed": "Max speed: 250km/h", "power": "400Cv", "torque": "500Nm", "engine": "2.5L inline 5-cylinder"}, "color": "Verde", "image": "/audi-rs3.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Audi RS3 Verde');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Audi RS3 Rossa', 39, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.8s", "power": "400Cv", "torque": "500Nm", "engine": "2.5L inline 5-cylinder"}, "color": "Rossa", "image": "/rs3.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Audi RS3 Rossa');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Mercedes A45 S AMG', 39, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.9s", "power": "421Cv", "torque": "500Nm", "engine": "2.0L 4-cylinder Turbo"}, "image": "/mercedes_amg.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Mercedes A45 S AMG');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'BMW M3 Competition', 49, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.9s", "maxSpeed": "Max speed: 250km/h", "power": "510Cv", "torque": "650Nm", "engine": "3.0L inline 6-cylinder"}, "image": "/bmw-m3.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'BMW M3 Competition');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'BMW M4 Competition', 59, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.8s", "power": "510Cv", "torque": "650Nm", "engine": "3.0L inline 6-cylinder"}, "image": "/bmw-m4.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'BMW M4 Competition');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Porsche Macan GTS', 69, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 4.5s", "power": "440Cv", "torque": "550Nm", "engine": "2.9L Twin-Turbo V6"}, "image": "/macan.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Porsche Macan GTS');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Mercedes GLE 63 AMG', 69, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.8s", "power": "612Cv", "torque": "850Nm", "engine": "4.0L V8 BiTurbo"}, "image": "/mercedes-gle.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Mercedes GLE 63 AMG');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Mercedes C63 S AMG', 99, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.9s", "power": "510Cv", "torque": "700Nm", "engine": "4.0L V8 BiTurbo"}, "image": "/c63.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Mercedes C63 S AMG');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Porsche 992 Carrera 4S', 119, 'available', 'exotic', '{"specs": {"acceleration": "0-100 in 3.6s", "maxSpeed": "Max speed: 306km/h", "power": "450Cv", "torque": "530Nm", "engine": "3.0L Twin-Turbo Flat-6"}, "image": "/porsche-911.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Porsche 992 Carrera 4S');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Fiat Panda', 29, 'available', 'urban', '{"specs": {"power": "70Cv", "engine": "1.2L", "seats": "5 posti"}, "image": "/panda.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Fiat Panda');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Citroen C5 Aircross', 29, 'available', 'urban', '{"specs": {"power": "130Cv", "engine": "1.5L BlueHDi", "seats": "5 posti"}, "image": "/c5.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Citroen C5 Aircross');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Fiat 500X', 39, 'available', 'urban', '{"specs": {"power": "120Cv", "engine": "1.3L MultiJet", "seats": "5 posti"}, "image": "/500x.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Fiat 500X');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'VW T-ROC', 49, 'available', 'urban', '{"specs": {"power": "150Cv", "engine": "1.5L TSI", "seats": "5 posti"}, "image": "/troc.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'VW T-ROC');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Cupra Formentor', 49, 'available', 'urban', '{"specs": {"power": "150Cv", "engine": "1.5L TSI", "seats": "5 posti"}, "image": "/cupra.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Cupra Formentor');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'VW Tiguan', 59, 'available', 'urban', '{"specs": {"power": "150Cv", "engine": "2.0L TDI", "seats": "5 posti"}, "image": "/tiguan.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'VW Tiguan');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Mercedes A250', 59, 'available', 'urban', '{"specs": {"power": "224Cv", "engine": "2.0L Turbo", "seats": "5 posti"}, "image": "/a250.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Mercedes A250');
INSERT INTO vehicles (display_name, daily_rate, status, category, metadata) SELECT 'Fiat Ducato Maxi', 79, 'available', 'urban', '{"specs": {"power": "140Cv", "engine": "2.3L MultiJet", "seats": "9 posti"}, "image": "/ducato.jpeg"}' WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE display_name = 'Fiat Ducato Maxi');

UPDATE vehicles SET category = 'exotic' WHERE display_name IN ('Audi RS3 Verde', 'Audi RS3 Rossa', 'Mercedes A45 S AMG', 'BMW M3 Competition', 'BMW M4 Competition', 'Porsche Macan GTS', 'Mercedes GLE 63 AMG', 'Mercedes C63 S AMG', 'Porsche 992 Carrera 4S');
UPDATE vehicles SET category = 'urban' WHERE display_name IN ('Fiat Panda', 'Citroen C5 Aircross', 'Fiat 500X', 'VW T-ROC', 'Cupra Formentor', 'VW Tiguan', 'Mercedes A250', 'Fiat Ducato Maxi');

SELECT display_name, daily_rate, category, status FROM vehicles ORDER BY category DESC, daily_rate;
